# fly.toml app configuration file generated for loglog-pocketbase-backend on 2025-03-12T16:35:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loglog-pocketbase-backend'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'pb_data'
  destination = '/pb/pb_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
