const BACKGROUND_POOP_CHECK_TASK_NAME = 'background-poop-check';
const BACKGROUND_POOP_CHECK_INTERVAL = 5 * 60 * 1000; // 5 minutes

export { BACKGROUND_POOP_CHECK_INTERVAL, BACKGROUND_POOP_CHECK_TASK_NAME };
